### ISSUE TITLE
Not-matching CRDs in helm Chart

### ISSUE THREAD

**Issue by KingCrunch** [bitnami/bitnami-docker-grafana-operator#1]
I don't know where to report issues with the Helm Chart

https://artifacthub.io/packages/helm/bitnami/grafana-operator

**Description**

Installing the helm chart 1.1.2, which corresponds to the application version 3.10.3 doesn't install the correct CRDs. Especially the properties `extraVolumeMounts`, `ingressClassName` and `pathType` are missing from the `Grafana´-CRD.

https://github.com/grafana-operator/grafana-operator/blob/v3.10.3/deploy/crds/Grafana.yaml

**Comment by juan131** [comment]
Hi @KingCrunch 

Thanks so much for reporting this!! Do you mind opening an issue in the Bitnami charts repository instead adding exactly the same information? See:

- https://github.com/bitnami/charts/issues

Thanks in advance!!

**Comment by KingCrunch** [comment]
Hi @juan131 

Thank You for pointing me to the right repository. I created a Pull Request 

https://github.com/bitnami/charts/pull/7441
