### ISSUE TITLE
Grafana 3.10.4

### ISSUE THREAD

**Issue by StianHaugland1** [bitnami/bitnami-docker-grafana-operator#2]
Grafana Operator version 3.10.4 was released yesterday. 🚀  

https://github.com/grafana-operator/grafana-operator/releases/tag/v3.10.4

**Comment by miguelaeh** [comment]
Hi @StianHaugland1 ,
Our system will detect the new version and release it once the new version passes all our tests

**Comment by carrodher** [comment]
The new version was released some days ago, see https://github.com/bitnami/bitnami-docker-grafana-operator/commit/b66ce2e268a0bc188a3d593af6ac9e966b2edb36.

I'm closing this issue
