### ISSUE TITLE
Grafana Operator 4.0.1 is available now

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/bitnami-docker-grafana-operator#3]
Hi Bitnami,

Grafana Operator 4.0.1 was released on Oct. 19, 2021 (6 days ago). 
There is already a PR for Bitnami Grafana Operator 4.0.1 Helm chart (https://github.com/bitnami/charts/pull/7896) .

Is anyone looking into how to introduce Bitnamis Grafana Operator 4.X.X docker image?
Thank you.

**Comment by FraPazGal** [comment]
Hello @nc-ruth,

We just released the container for the new major grafana-operator@4, packaged with the latest version `4.0.2`. There were a few issues that required some internal work, thank you for the patience!

**Comment by nc-ruth** [comment]
@FraPazGal thank you for the update!
I will check it out and test it next week :)
